### ISSUE TITLE
Remove an ignore .DS_Store files

### ISSUE THREAD

**Issue by juliendargelos** [panGenerator/tweakpane-textarea-plugin#3]
I noticed there is a [.DS_Store file](https://github.com/panGenerator/tweakpane-textarea-plugin/blob/5f353cb1a2db7f61123e05d65a4282370f85c5e4/.DS_Store) from Mac OS file system in your git tree, it should be removed then added to .gitignore to avoid polluting the tree in further commits.

**Comment by juliendargelos** [comment]
I appreciate your reactivity :)
However you forgot to commit the removal of existing .DS_Store files before adding them to .gitignore so they are still remaining on github. For github to actually acknowledge the removal, you would have to revert your previous commit by removing the corresponding line in the .gitignore, remove all .DS_Store files, commit and push. Then add back the line in the .gitignore, and commit and push again.

**Comment by kgolinski** [comment]
That should be ok now
